# import logging
# from venv import logger

# from django.core.exceptions import ValidationError

# from foodgram_backend.translat_dict import get_name as _

# logging.basicConfig(level=logging.INFO)


# # def validate_subscription(value):
# #     logger.info(f"~~~~~ VALIDATOR: {type(value)} {value}\n")
# #     if value.follower == value.following:
# #         raise ValidationError(_('User can not create self subscription.'))
